### ISSUE TITLE
can we use it in production env?

### ISSUE THREAD

**Issue by Brooooooklyn** [arthurhsu/rdb-polyfill#6]
We have built a [database adapter](https://github.com/teambition/reactivedb) for lovefield.
but as you know, lovefield is not module friendly and too huge for frontend project.

So I'm wondering if we could use `rdb-polyfill` instead of lovefield in our production.

**Comment by arthurhsu** [comment]
rdb-polyfill only runs on Node.js so far and is not even finished yet. It's my personal pet project and is not backed by Google. By using rdb-polyfill you assume all risks and there will be no support.
